// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;



// Model definition for `evolute_duel::eventsModels::EGameCreated` model
public class evolute_duel_TrophyProgression : ModelInstance {
        [ModelField("player_id")]
        public FieldElement player_id;
        
        [ModelField("task_id")]
        public FieldElement task_id;
        
        [ModelField("count")]
        public uint count;
        
        [ModelField("time")]
        public ulong time;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        