// Generated by dojo-bindgen on Wed, 28 May 2025 17:47:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::scoring::UnionFind` model
public class evolute_duel_UnionFind : ModelInstance {
    [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("nodes_parents")]
        public byte[] nodes_parents;

        [ModelField("nodes_ranks")]
        public byte[] nodes_ranks;

        [ModelField("nodes_blue_points")]
        public ushort[] nodes_blue_points;

        [ModelField("nodes_red_points")]
        public ushort[] nodes_red_points;

        [ModelField("nodes_open_edges")]
        public byte[] nodes_open_edges;

        [ModelField("nodes_contested")]
        public bool[] nodes_contested;

        [ModelField("nodes_types")]
        public byte[] nodes_types;

        [ModelField("potential_city_contests")]
        public byte[] potential_city_contests;

        [ModelField("potential_road_contests")]
        public byte[] potential_road_contests;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        