// Generated by dojo-bindgen on Sun, 23 Feb 2025 13:49:03 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using TerritoryWars.Models;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `evolute_duel::models::CityNode` model
public class evolute_duel_CityNode : ModelInstance, INode {
    [ModelField("board_id")]
        public FieldElement board_id;

        [ModelField("position")]
        public byte position;

        [ModelField("parent")]
        public byte parent;

        [ModelField("rank")]
        public byte rank;

        [ModelField("blue_points")]
        public ushort blue_points;

        [ModelField("red_points")]
        public ushort red_points;

        [ModelField("open_edges")]
        public byte open_edges;

        [ModelField("contested")]
        public bool contested;

    public byte GetPosition() {
        return position;
    }
    
    public ushort GetBluePoints() {
        return (byte)blue_points;
    }
    
    public ushort GetRedPoints() {
        return (byte)red_points;
    }
    
    public byte GetOpenEdges() {
        return open_edges;
    }
    
    
}

        