// Generated by dojo-bindgen on Mon, 4 Nov 2024 23:36:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `evolute_duel::models::Message` model
public class evolute_duel_Message : ModelInstance {
    [ModelField("identity")]
    public FieldElement identity;

    [ModelField("channel")]
    public FieldElement channel;

    [ModelField("message")]
    public string message;

    [ModelField("salt")]
    public FieldElement salt;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
} 