// Generated by dojo-bindgen on Mon, 24 Feb 2025 09:31:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

[Serializable]
public struct TrophyTask
{
    public FieldElement id;
    public uint total;
    public byte[] description;
}

// Model definition for `evolute_duel::eventsModels::EGameCreated` model
public class evolute_duel_TrophyCreation : ModelInstance {
        [ModelField("id")]
        public FieldElement id;
        
        [ModelField("hidden")]
        public bool hidden;
        
        [ModelField("index")]
        public byte index;
        
        [ModelField("points")]
        public ushort points;
        
        [ModelField("start")]
        public ulong start;
        
        [ModelField("end")]
        public ulong end;
        
        [ModelField("group")]
        public FieldElement group;
        
        [ModelField("icon")]
        public FieldElement icon;
        
        [ModelField("title")]
        public FieldElement title;
        
        [ModelField("description")]
        public byte[] description;
        
        [ModelField("tasks")]
        public TrophyTask[] tasks;
        
        [ModelField("data")]
        public byte[] data;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        